driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.7
  - name: centos-7.1
  - name: ubuntu-12.04
    run_list:
      - recipe[apt::default]
  - name: ubuntu-14.04
    run_list:
      - recipe[apt::default]

suites:
  - name: default
    run_list:
      - recipe[rsync::default]
  - name: simple
    run_list:
      - recipe[fake::simple]
  - name: read_only
    run_list:
      - recipe[fake::read_only]
  - name: networking
    run_list:
      - recipe[fake::networking]
