driver_plugin: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
  - name: centos-6.6

suites:
  - name: default
    run_list:
      - recipe[rsync::default]
  - name: simple
    run_list:
      - recipe[fake::simple]
  - name: read_only
    run_list:
      - recipe[fake::read_only]
  - name: networking
    run_list:
      - recipe[fake::networking]
