driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-6
  - name: centos-7
  - name: debian-7
  - name: debian-8
  - name: debian-9
  - name: fedora-26
  - name: opensuse-leap-42
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[test::default]
  - name: simple
    run_list:
      - recipe[test::simple]
  - name: read-only
    run_list:
      - recipe[test::read_only]
  - name: networking
    run_list:
      - recipe[test::networking]
