sudo: required
dist: trusty

addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk

# Don't `bundle install` which takes about 1.5 mins
install: echo "skip bundle install"

branches:
  only:
    - master

services: docker

env:
  matrix:
  - INSTANCE=default-ubuntu-1404
  - INSTANCE=default-ubuntu-1604
  - INSTANCE=default-centos-7
  - INSTANCE=default-centos-6
  - INSTANCE=simple-ubuntu-1404
  - INSTANCE=simple-ubuntu-1604
  - INSTANCE=simple-centos-7
  - INSTANCE=simple-centos-6
  - INSTANCE=read-only-ubuntu-1404
  - INSTANCE=read-only-ubuntu-1604
  - INSTANCE=read-only-centos-7
  - INSTANCE=read-only-centos-6
  - INSTANCE=networking-ubuntu-1404
  - INSTANCE=networking-ubuntu-1604
  - INSTANCE=networking-centos-7
  - INSTANCE=networking-centos-6

  fast_finish: true

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(chef shell-init bash)"

script: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen verify ${INSTANCE}

matrix:
  include:
    - before_script:
      - eval "$(chef shell-init bash)"
      - chef --version
      - cookstyle --version
      - foodcritic --version
    - script:
      - chef exec delivery local all
      env: UNIT_AND_LINT=1
